[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["debug", "image", "svg", "tokio"] }
backend = { path = "../backend" }
resvg = "0.43.0"
tiny-skia = "0.11.4"
usvg = "0.43.0"
