[package]
name = "wish"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["debug", "image", "svg", "tokio"] }
rand = "0.8.5"
rayon = "1.10.0"
resvg = "0.43.0"
tiny-skia = "0.11.4"
usvg = "0.43.0"
