name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build release
        run: cargo build --release

      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          REPO_VERSION=$(grep -E '^version = "(.*)"' Cargo.toml | cut -d '"' -f 2)
          echo "REPO_VERSION=$REPO_VERSION" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.REPO_VERSION }}
          name: Wish Planner
          body: "Plan your wishes ahead!"
